config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#show', as: :root

  resources :questions do
    get :follow, on: :member
    get :unfollow, on: :member
  end
  resources :answers, only: [:create] do
    get :vote_up, on: :member
    get :vote_down, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  has_many :votes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :user_questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :user_questions
  has_many :answers
end

app/models/user_question.rb
class UserQuestion < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :answer
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    question = Question.find_by!(id: answer_params[:question_id])

    current_user
      .answers
      .create(answer_params)

    question.update(updated_at: Time.now)

    redirect_to question_path(question)
  end

  def vote_up
    answer = Answer.find_by!(id: params[:id])
    answer.votes.create(user: current_user, value: true)
    redirect_to question_path(answer.question_id)
  end

  def vote_down
    answer = Answer.find_by!(id: params[:id])
    answer.votes.create(user: current_user, value: false)
    redirect_to question_path(answer.question_id)
  end

  private

  def answer_params
    params
      .require(:answer)
      .permit(:question_id, :text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @questions = Question
                 .joins(:user_questions)
                 .where(user_questions: { user_id: current_user.id })
                 .order(updated_at: :desc)

    redirect_to questions_path if @questions.none?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(updated_at: :desc).all
  end

  def show
    @question = Question.find_by(id: params[:id])
  end

  def create
    @question = current_user
                .questions
                .create(question_params)

    current_user
      .user_questions
      .create(question: @question)

    redirect_to question_path(@question)
  rescue => error
    flash.now[:error] = error.message
    render :new
  end

  def update
    @question = current_user
                .questions
                .find_by(id: params[:id])

    @question.update(question_params)

    redirect_to question_path(@question)
  rescue => error
    flash.now[:error] = error.message
    render :edit
  end

  def destroy
    @question = current_user
                .questions
                .find_by(id: params[:id])

    @question.destroy
    redirect_to questions_path
  end

  def follow
    @question = Question.find_by(id: params[:id])

    current_user
      .user_questions
      .where(question: @question)
      .first_or_create

    redirect_to question_path(@question)
  end

  def unfollow
    @question = Question.find_by(id: params[:id])

    current_user
      .user_questions
      .where(question: @question)
      .delete_all

    redirect_to question_path(@question)
  end

  def new; end

  private

  def question_params
    params
      .require(:question)
      .permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def toastr_flashes
    flash_messages = []
    flash.each do |type, message|
      if message.present?
        type = case type.to_sym
               when :notice
                 'success'
               when :success
                 'success'
               when :alert
                 'error'
               when :error
                 'error'
               when :warning
                 'warning'
               when :info
                 'info'
               end
        text = "<script>$(function() { toastr.#{type}('#{j message}'); });</script>"
        flash_messages << text.html_safe
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/answers/_new.html.erb
<div class="answer">
  <div class="form">
    <hr>
    <%= form_for @question.answers.new do |f| %>
      <span><%= I18n.t('questions.fields.description') %></span>
      <br>
      <%= f.text_area :text, size: "60x12" %>
      <%= f.hidden_field :question_id, value: @question.id %>
      <br>
      <%= f.submit I18n.t('questions.submit') %>
    <% end %>
  </div>
</div>

app/views/answers/_show.html.erb
<li>
  <dt>
    <% can_vote = answer.user_id != current_user.id && !answer.votes.find { |vote| vote.user_id == current_user.id } %>
    <% if can_vote %>
      <%= link_to '+', vote_up_answer_path(answer) %>
    <% end %>
    <%= answer.votes.sum { |r| r.value ? 1 : -1 } %>
    <% if can_vote %>
        <%= link_to '-', vote_down_answer_path(answer) %>
    <% end %>
  </dt>
  <dd>
    <%= answer.text %>
  </dd>
</li>

app/views/home/show.html.erb
<div class="list">
  <dl>
    <% @questions.each do |question| %>
        <div class="list-item">
          <li class="left tal">
            <%= link_to(question.title, question_path(question)) %>
          </li>
        </div>
    <% end %>
  </dl>
</div>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %meta{charset: 'utf-8'}/
    %meta{content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport'}/
    %title= 'Engineering.ai challenge'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = toastr_flashes
  %body
    %header
      .d-flex.flex-column.flex-md-row.align-items-center.p-1.px-md-4.mb-3.bg-white.border-bottom.shadow-sm
        %h5.my-0.mr-md-auto.font-weight-normal= link_to 'Engineering.ai challenge', root_path
        %nav.my-2.my-md-0.mr-md-3
          %a.p-2.text-dark= link_to(I18n.t('questions.title'), questions_path)

        - if signed_in?
          %span.m-2= "#{current_user.email}"
          = link_to t('common.sign_out'), destroy_user_session_path, method: :delete, class: 'm-2 btn btn-secondary'
        - else
          = link_to t('common.sign_in'), user_session_path, class: 'm-1 btn btn-primary'
          = link_to t('common.sign_up'), new_user_registration_path, class: 'm-2 btn btn-success'
    %main.container{role: 'main'}
      .px-5.py-2
        = yield

app/views/questions/_form.html.erb
<%= form_for question do |f| %>
  <span><%= I18n.t('questions.fields.title') %></span>
  <br>
  <%= f.text_field :title, size: "61" %>
  <br>
  <span><%= I18n.t('questions.fields.description') %></span>
  <br>
  <%= f.text_area :description, size: "60x12" %>
  <br>
  <%= f.submit I18n.t('questions.submit') %>
<% end %>

app/views/questions/edit.html.erb
<div class="question">
  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="top tar">
  <%= link_to(I18n.t('questions.new'), new_question_path) %>
</div>

<div class="list">
  <dl>
    <% @questions.each do |question| %>
      <div class="list-item">
        <li class="left tal">
          <%= link_to(question.title, question_path(question)) %>
        </li>
      </div>
    <% end %>
  </dl>
</div>

app/views/questions/new.html.erb
<div class="question">
  <%= render 'form', question: current_user.questions.new %>
</div>

app/views/questions/show.html.erb
<div class="top tar">
  <%= link_to(I18n.t('common.back'), questions_path) %>
  <br>
  <% if current_user.id == @question.user_id %>
    <%= link_to(I18n.t('questions.edit'), edit_question_path(@question)) %>
  <% end %>
  <br>
  <% if current_user.user_questions.where(question: @question).exists? %>
      <%= link_to(I18n.t('questions.unfollow'), unfollow_question_path(@question)) %>
  <% else %>
      <%= link_to(I18n.t('questions.follow'), follow_question_path(@question)) %>
  <% end %>
</div>

<div class="question">
  <div class="details">
    <h3><%= @question.title %></h3>
    <hr>
    <p><%= @question.description %></p>
    <hr>
  </div>
  <div class="answers">
    <div class="list">
      <dl>
        <% @question.answers.preload(:votes).each do |answer| %>
          <%= render 'answers/show', answer: answer %>
        <% end %>
      </dl>
    </div>
  </div>
</div>

<% unless current_user.id == @question.user_id %>
  <%= render 'answers/new' %>
<% end %>